import { FieldConfig } from 'src/app/shared/components/form-components/models/field-config';
// tslint:disable: quotemark

export const $sex: FieldConfig = {
    label: 'Sexo',
    options: [
        {
            value: 'FEMENINO',
            viewValue: 'FEMENINO'
        },
        {
            value: 'MASCULINO',
            viewValue: 'MASCULINO'
        }
    ]
};

export const $family: FieldConfig = {
    label: 'Parentesco / Vinculación',
    name: 'family',
    options: [
        { value: 'CONYUGE', viewValue: 'CÓNYUGE' },
        { value: 'HIJO', viewValue: 'HIJO' },
        { value: 'HIJA', viewValue: 'HIJA' },
        { value: 'ABUELO', viewValue: 'ABUELO' },
        { value: 'ABUELA', viewValue: 'ABUELA' },
        { value: 'TIO', viewValue: 'TIO' },
        { value: 'TIA', viewValue: 'TIA' },
        { value: 'HERMANA', viewValue: 'HERMANA' },
        { value: 'HERMANO', viewValue: 'HERMANO' },
        { value: 'PADRE', viewValue: 'PADRE' },
        { value: 'MADRE', viewValue: 'MADRE' },
        { value: 'HEREDEROS LEGALES', viewValue: 'HEREDEROS LEGALES' },
        { value: 'SOBRINO', viewValue: 'SOBRINO' },
        { value: 'SOBRINA', viewValue: 'SOBRINA' },
        { value: 'NIETO', viewValue: 'NIETO' },
        { value: 'NIETA', viewValue: 'NIETA' },
        { value: 'ACREEDOR', viewValue: 'ACREEDOR' },
        { value: 'SUEGRA', viewValue: 'SUEGRA' },
        { value: 'SUEGRO', viewValue: 'SUEGRO' },
        { value: 'HIJASTRA', viewValue: 'HIJASTRA' },
        { value: 'HIJASTRO', viewValue: 'HIJASTRO' },
        { value: 'TUTOR', viewValue: 'TUTOR' },
        { value: 'CESIONARIO', viewValue: 'CESIONARIO' },
        { value: 'CONTINGENTE', viewValue: 'CONTINGENTE' },
        { value: 'ACOMPAÑANTE', viewValue: 'ACOMPAÑANTE' },
        { value: 'AMIGO', viewValue: 'AMIGO' },
        { value: 'AMIGA', viewValue: 'AMIGA' },
        { value: 'CUÑADA', viewValue: 'CUÑADA' },
        { value: 'RELACIONADO', viewValue: 'RELACIONADO' },
        { value: 'COMADRE', viewValue: 'COMADRE' },
        { value: 'COMPADRE', viewValue: 'COMPADRE' },
        { value: 'COMPAÑERA', viewValue: 'COMPAÑERA' },
        { value: 'COMPAÑERO', viewValue: 'COMPAÑERO' },
        { value: 'COMPAÑÍA', viewValue: 'COMPAÑÍA' },
        { value: 'CONTRATANTE', viewValue: 'CONTRATANTE' },
        { value: 'CONYUGE', viewValue: 'CONYUGE' },
        { value: 'COMPAÑERO DE VIDA', viewValue: 'COMPAÑERO DE VIDA' },
        { value: 'CUÑADO', viewValue: 'CUÑADO' },
        { value: 'PATRONO', viewValue: 'PATRONO' },
        { value: 'EX ESPOSA', viewValue: 'EX ESPOSA' },
        { value: 'EX ESPOSO', viewValue: 'EX ESPOSO' },
        { value: 'FAMILIAR', viewValue: 'FAMILIAR' },
        { value: 'HIJA ADOPTIVA', viewValue: 'HIJA ADOPTIVA' },
        { value: 'HIJO ADOPTIVO', viewValue: 'HIJO ADOPTIVO' },
        { value: 'HIJA DE CRIANZA', viewValue: 'HIJA DE CRIANZA' },
        { value: 'HIJO DE CRIANZA', viewValue: 'HIJO DE CRIANZA' },
        { value: 'HERMANA DE CRIANZA', viewValue: 'HERMANA DE CRIANZA' },
        { value: 'HERMANO DE CRIANZA', viewValue: 'HERMANO DE CRIANZA' },
        { value: 'MADRASTA', viewValue: 'MADRASTA' },
        { value: 'PADRASTO', viewValue: 'PADRASTO' },
        { value: 'MADRE DE CRIANZA', viewValue: 'MADRE DE CRIANZA' },
        { value: 'PADRE DE CRIANZA', viewValue: 'PADRE DE CRIANZA' },
        { value: 'MADRE DE LOS HIJOS', viewValue: 'MADRE DE LOS HIJOS' },
        { value: 'PADRE DE LOS HIJOS', viewValue: 'PADRE DE LOS HIJOS' },
        { value: 'MADRINA', viewValue: 'MADRINA' },
        { value: 'PADRINO', viewValue: 'PADRINO' },
        { value: 'NO DECLARADO', viewValue: 'NO DECLARADO' },
        { value: 'NOVIA', viewValue: 'NOVIA' },
        { value: 'NOVIO', viewValue: 'NOVIO' },
        { value: 'PASTOR DE LA IGLESIA', viewValue: 'PASTOR DE LA IGLESIA' },
        { value: 'PATRONO', viewValue: 'PATRONO' },
        { value: 'PRIMA', viewValue: 'PRIMA' },
        { value: 'PRIMO', viewValue: 'PRIMO' },
        { value: 'PROTEGIDA', viewValue: 'PROTEGIDA' },
        { value: 'PROTEGIDO', viewValue: 'PROTEGIDO' },
        { value: 'SOCIA', viewValue: 'SOCIA' },
        { value: 'SOCIO', viewValue: 'SOCIO' },
        { value: 'SOCIEDAD ANONIMA', viewValue: 'SOCIEDAD ANONIMA' },
        { value: 'TUTORA', viewValue: 'TUTORA' },
        { value: 'TUTOR', viewValue: 'TUTOR' },
        { value: 'TUTORES LEGALES', viewValue: 'TUTORES LEGALES' },
        { value: 'EMPLEADO', viewValue: 'EMPLEADO' },
        { value: 'HIJO ADULTO', viewValue: 'HIJO ADULTO' },
        { value: 'HIJA ADULTA', viewValue: 'HIJA ADULTA' },
        { value: 'YERNO', viewValue: 'YERNO' },
        { value: 'OTROS', viewValue: 'OTROS' },
    ]
};

export const $res: FieldConfig = {
    options: [
        {
            value: true,
            viewValue: 'Si'
        },
        {
            value: false,
            viewValue: 'No'
        }
    ]
};

export const $weightTypes = [
    {
        value: 'KILOGRAMOS',
        viewValue: "Kg"
    },
    {
        value: 'LIBRAS',
        viewValue: "Lb",
    },
];

export const $heightTypes = [
    {
        value: 'PIE',
        viewValue: 'PIE'
    },
    {
        value: 'METRO',
        viewValue: "METRO",
    },
];

export const $country =
    [
        { value: "AFGANISTÁN", viewValue: "AFGANISTÁN" },
        { value: "ALANDIA", viewValue: "ALANDIA" },
        { value: "ALBANIA", viewValue: "ALBANIA" },
        { value: "ALEMANIA", viewValue: "ALEMANIA" },
        { value: "ANDORRA", viewValue: "ANDORRA" },
        { value: "ANGOLA", viewValue: "ANGOLA" },
        { value: "ANGUILLA", viewValue: "ANGUILLA" },
        { value: "ANTIGUA Y BARBUDA", viewValue: "ANTIGUA Y BARBUDA" },
        { value: "ANTÁRTIDA", viewValue: "ANTÁRTIDA" },
        { value: "ARABIA SAUDÍ", viewValue: "ARABIA SAUDÍ" },
        { value: "ARGELIA", viewValue: "ARGELIA" },
        { value: "ARGENTINA", viewValue: "ARGENTINA" },
        { value: "ARMENIA", viewValue: "ARMENIA" },
        { value: "ARUBA", viewValue: "ARUBA" },
        { value: "AUSTRALIA", viewValue: "AUSTRALIA" },
        { value: "AUSTRIA", viewValue: "AUSTRIA" },
        { value: "AZERBAIYÁN", viewValue: "AZERBAIYÁN" },
        { value: "BAHAMAS", viewValue: "BAHAMAS" },
        { value: "BAHREIN", viewValue: "BAHREIN" },
        { value: "BANGLADESH", viewValue: "BANGLADESH" },
        { value: "BARBADOS", viewValue: "BARBADOS" },
        { value: "BELICE", viewValue: "BELICE" },
        { value: "BENÍN", viewValue: "BENÍN" },
        { value: "BERMUDAS", viewValue: "BERMUDAS" },
        { value: "BIELORRUSIA", viewValue: "BIELORRUSIA" },
        { value: "BOLIVIA", viewValue: "BOLIVIA" },
        { value: "BONAIRE, SAN EUSTAQUIO Y SABA", viewValue: "BONAIRE, SAN EUSTAQUIO Y SABA" },
        { value: "BOSNIA Y HERZEGOVINA", viewValue: "BOSNIA Y HERZEGOVINA" },
        { value: "BOTSWANA", viewValue: "BOTSWANA" },
        { value: "BRASIL", viewValue: "BRASIL" },
        { value: "BRUNEI", viewValue: "BRUNEI" },
        { value: "BULGARIA", viewValue: "BULGARIA" },
        { value: "BURKINA FASO", viewValue: "BURKINA FASO" },
        { value: "BURUNDI", viewValue: "BURUNDI" },
        { value: "BUTÁN", viewValue: "BUTÁN" },
        { value: "BÉLGICA", viewValue: "BÉLGICA" },
        { value: "CABO VERDE", viewValue: "CABO VERDE" },
        { value: "CAMBOYA", viewValue: "CAMBOYA" },
        { value: "CAMERÚN", viewValue: "CAMERÚN" },
        { value: "CANADÁ", viewValue: "CANADÁ" },
        { value: "CATAR", viewValue: "CATAR" },
        { value: "CHAD", viewValue: "CHAD" },
        { value: "CHILE", viewValue: "CHILE" },
        { value: "CHINA", viewValue: "CHINA" },
        { value: "CHIPRE", viewValue: "CHIPRE" },
        { value: "COLOMBIA", viewValue: "COLOMBIA" },
        { value: "COMORAS", viewValue: "COMORAS" },
        { value: "CONGO", viewValue: "CONGO" },
        { value: "CONGO (REP. DEM.)", viewValue: "CONGO (REP. DEM.)" },
        { value: "COREA DEL NORTE", viewValue: "COREA DEL NORTE" },
        { value: "COREA DEL SUR", viewValue: "COREA DEL SUR" },
        { value: "COSTA DE MARFIL", viewValue: "COSTA DE MARFIL" },
        { value: "COSTA RICA", viewValue: "COSTA RICA" },
        { value: "CROACIA", viewValue: "CROACIA" },
        { value: "CUBA", viewValue: "CUBA" },
        { value: "CURAZAO", viewValue: "CURAZAO" },
        { value: "DINAMARCA", viewValue: "DINAMARCA" },
        { value: "DOMINICA", viewValue: "DOMINICA" },
        { value: "ECUADOR", viewValue: "ECUADOR" },
        { value: "EGIPTO", viewValue: "EGIPTO" },
        { value: "EL SALVADOR", viewValue: "EL SALVADOR" },
        { value: "EMIRATOS ÁRABES UNIDOS", viewValue: "EMIRATOS ÁRABES UNIDOS" },
        { value: "ERITREA", viewValue: "ERITREA" },
        { value: "ESLOVENIA", viewValue: "ESLOVENIA" },
        { value: "ESPAÑA", viewValue: "ESPAÑA" },
        { value: "ESTADOS UNIDOS", viewValue: "ESTADOS UNIDOS" },
        { value: "ESTONIA", viewValue: "ESTONIA" },
        { value: "ETIOPÍA", viewValue: "ETIOPÍA" },
        { value: "FILIPINAS", viewValue: "FILIPINAS" },
        { value: "FINLANDIA", viewValue: "FINLANDIA" },
        { value: "FIYI", viewValue: "FIYI" },
        { value: "FRANCIA", viewValue: "FRANCIA" },
        { value: "GABÓN", viewValue: "GABÓN" },
        { value: "GAMBIA", viewValue: "GAMBIA" },
        { value: "GEORGIA", viewValue: "GEORGIA" },
        { value: "GHANA", viewValue: "GHANA" },
        { value: "GIBRALTAR", viewValue: "GIBRALTAR" },
        { value: "GRECIA", viewValue: "GRECIA" },
        { value: "GRENADA", viewValue: "GRENADA" },
        { value: "GROENLANDIA", viewValue: "GROENLANDIA" },
        { value: "GUADALUPE", viewValue: "GUADALUPE" },
        { value: "GUAM", viewValue: "GUAM" },
        { value: "GUATEMALA", viewValue: "GUATEMALA" },
        { value: "GUAYANA FRANCESA", viewValue: "GUAYANA FRANCESA" },
        { value: "GUERNSEY", viewValue: "GUERNSEY" },
        { value: "GUINEA", viewValue: "GUINEA" },
        { value: "GUINEA ECUATORIAL", viewValue: "GUINEA ECUATORIAL" },
        { value: "GUINEA-BISÁU", viewValue: "GUINEA-BISÁU" },
        { value: "GUYANA", viewValue: "GUYANA" },
        { value: "HAITI", viewValue: "HAITI" },
        { value: "HONDURAS", viewValue: "HONDURAS" },
        { value: "HONG KONG", viewValue: "HONG KONG" },
        { value: "HUNGRÍA", viewValue: "HUNGRÍA" },
        { value: "INDIA", viewValue: "INDIA" },
        { value: "INDONESIA", viewValue: "INDONESIA" },
        { value: "IRAK", viewValue: "IRAK" },
        { value: "IRAN", viewValue: "IRAN" },
        { value: "IRLANDA", viewValue: "IRLANDA" },
        { value: "ISLA BOUVET", viewValue: "ISLA BOUVET" },
        { value: "ISLA DE MAN", viewValue: "ISLA DE MAN" },
        { value: "ISLA DE NAVIDAD", viewValue: "ISLA DE NAVIDAD" },
        { value: "ISLA DE NORFOLK", viewValue: "ISLA DE NORFOLK" },
        { value: "ISLANDIA", viewValue: "ISLANDIA" },
        { value: "ISLAS CAIMÁN", viewValue: "ISLAS CAIMÁN" },
        { value: "ISLAS COCOS O ISLAS KEELING", viewValue: "ISLAS COCOS O ISLAS KEELING" },
        { value: "ISLAS COOK", viewValue: "ISLAS COOK" },
        { value: "ISLAS FAROE", viewValue: "ISLAS FAROE" },
        { value: "ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR", viewValue: "ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR" },
        { value: "ISLAS HEARD Y MCDONALD", viewValue: "ISLAS HEARD Y MCDONALD" },
        { value: "ISLAS MALVINAS", viewValue: "ISLAS MALVINAS" },
        { value: "ISLAS MARIANAS DEL NORTE", viewValue: "ISLAS MARIANAS DEL NORTE" },
        { value: "ISLAS MARSHALL", viewValue: "ISLAS MARSHALL" },
        { value: "ISLAS PITCAIRN", viewValue: "ISLAS PITCAIRN" },
        { value: "ISLAS SALOMÓN", viewValue: "ISLAS SALOMÓN" },
        { value: "ISLAS SVALBARD Y JAN MAYEN", viewValue: "ISLAS SVALBARD Y JAN MAYEN" },
        { value: "ISLAS TOKELAU", viewValue: "ISLAS TOKELAU" },
        { value: "ISLAS TURKS Y CAICOS", viewValue: "ISLAS TURKS Y CAICOS" },
        { value: "ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS", viewValue: "ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS" },
        { value: "ISLAS VÍRGENES DE LOS ESTADOS UNIDOS", viewValue: "ISLAS VÍRGENES DE LOS ESTADOS UNIDOS" },
        { value: "ISLAS VÍRGENES DEL REINO UNIDO", viewValue: "ISLAS VÍRGENES DEL REINO UNIDO" },
        { value: "ISRAEL", viewValue: "ISRAEL" },
        { value: "ITALIA", viewValue: "ITALIA" },
        { value: "JAMAICA", viewValue: "JAMAICA" },
        { value: "JAPÓN", viewValue: "JAPÓN" },
        { value: "JERSEY", viewValue: "JERSEY" },
        { value: "JORDANIA", viewValue: "JORDANIA" },
        { value: "KAZAJISTÁN", viewValue: "KAZAJISTÁN" },
        { value: "KENIA", viewValue: "KENIA" },
        { value: "KIRGUIZISTÁN", viewValue: "KIRGUIZISTÁN" },
        { value: "KIRIBATI", viewValue: "KIRIBATI" },
        { value: "KOSOVO", viewValue: "KOSOVO" },
        { value: "KUWAIT", viewValue: "KUWAIT" },
        { value: "LAOS", viewValue: "LAOS" },
        { value: "LESOTHO", viewValue: "LESOTHO" },
        { value: "LETONIA", viewValue: "LETONIA" },
        { value: "LIBERIA", viewValue: "LIBERIA" },
        { value: "LIBIA", viewValue: "LIBIA" },
        { value: "LIECHTENSTEIN", viewValue: "LIECHTENSTEIN" },
        { value: "LITUANIA", viewValue: "LITUANIA" },
        { value: "LUXEMBURGO", viewValue: "LUXEMBURGO" },
        { value: "LÍBANO", viewValue: "LÍBANO" },
        { value: "MACAO", viewValue: "MACAO" },
        { value: "MACEDONIA", viewValue: "MACEDONIA" },
        { value: "MADAGASCAR", viewValue: "MADAGASCAR" },
        { value: "MALASIA", viewValue: "MALASIA" },
        { value: "MALAWI", viewValue: "MALAWI" },
        { value: "MALDIVAS", viewValue: "MALDIVAS" },
        { value: "MALI", viewValue: "MALI" },
        { value: "MALTA", viewValue: "MALTA" },
        { value: "MARRUECOS", viewValue: "MARRUECOS" },
        { value: "MARTINICA", viewValue: "MARTINICA" },
        { value: "MAURICIO", viewValue: "MAURICIO" },
        { value: "MAURITANIA", viewValue: "MAURITANIA" },
        { value: "MAYOTTE", viewValue: "MAYOTTE" },
        { value: "MICRONESIA", viewValue: "MICRONESIA" },
        { value: "MOLDAVIA", viewValue: "MOLDAVIA" },
        { value: "MONGOLIA", viewValue: "MONGOLIA" },
        { value: "MONTENEGRO", viewValue: "MONTENEGRO" },
        { value: "MONTSERRAT", viewValue: "MONTSERRAT" },
        { value: "MOZAMBIQUE", viewValue: "MOZAMBIQUE" },
        { value: "MYANMAR", viewValue: "MYANMAR" },
        { value: "MÉXICO", viewValue: "MÉXICO" },
        { value: "MÓNACO", viewValue: "MÓNACO" },
        { value: "NAMIBIA", viewValue: "NAMIBIA" },
        { value: "NAURU", viewValue: "NAURU" },
        { value: "NEPAL", viewValue: "NEPAL" },
        { value: "NICARAGUA", viewValue: "NICARAGUA" },
        { value: "NIGERIA", viewValue: "NIGERIA" },
        { value: "NIUE", viewValue: "NIUE" },
        { value: "NORUEGA", viewValue: "NORUEGA" },
        { value: "NUEVA CALEDONIA", viewValue: "NUEVA CALEDONIA" },
        { value: "NUEVA ZELANDA", viewValue: "NUEVA ZELANDA" },
        { value: "NÍGER", viewValue: "NÍGER" },
        { value: "OMÁN", viewValue: "OMÁN" },
        { value: "PAKISTÁN", viewValue: "PAKISTÁN" },
        { value: "PALAU", viewValue: "PALAU" },
        { value: "PALESTINA", viewValue: "PALESTINA" },
        { value: "PANAMÁ", viewValue: "PANAMÁ" },
        { value: "PAPÚA NUEVA GUINEA", viewValue: "PAPÚA NUEVA GUINEA" },
        { value: "PARAGUAY", viewValue: "PARAGUAY" },
        { value: "PAÍSES BAJOS", viewValue: "PAÍSES BAJOS" },
        { value: "PERÚ", viewValue: "PERÚ" },
        { value: "POLINESIA FRANCESA", viewValue: "POLINESIA FRANCESA" },
        { value: "POLONIA", viewValue: "POLONIA" },
        { value: "PORTUGAL", viewValue: "PORTUGAL" },
        { value: "PUERTO RICO", viewValue: "PUERTO RICO" },
        { value: "REINO UNIDO", viewValue: "REINO UNIDO" },
        { value: "REPÚBLICA CENTROAFRICANA", viewValue: "REPÚBLICA CENTROAFRICANA" },
        { value: "REPÚBLICA CHECA", viewValue: "REPÚBLICA CHECA" },
        { value: "REPÚBLICA DE SUDÁFRICA", viewValue: "REPÚBLICA DE SUDÁFRICA" },
        { value: "REPÚBLICA DOMINICANA", viewValue: "REPÚBLICA DOMINICANA" },
        { value: "REPÚBLICA ESLOVACA", viewValue: "REPÚBLICA ESLOVACA" },
        { value: "REUNIÓN", viewValue: "REUNIÓN" },
        { value: "RUANDA", viewValue: "RUANDA" },
        { value: "RUMANIA", viewValue: "RUMANIA" },
        { value: "RUSIA", viewValue: "RUSIA" },
        { value: "SAHARA OCCIDENTAL", viewValue: "SAHARA OCCIDENTAL" },
        { value: "SAINT MARTIN", viewValue: "SAINT MARTIN" },
        { value: "SAMOA", viewValue: "SAMOA" },
        { value: "SAMOA AMERICANA", viewValue: "SAMOA AMERICANA" },
        { value: "SAN BARTOLOMÉ", viewValue: "SAN BARTOLOMÉ" },
        { value: "SAN CRISTÓBAL Y NIEVES", viewValue: "SAN CRISTÓBAL Y NIEVES" },
        { value: "SAN MARINO", viewValue: "SAN MARINO" },
        { value: "SAN MARTÍN (PAÍSES BAJOS)", viewValue: "SAN MARTÍN (PAÍSES BAJOS)" },
        { value: "SAN PEDRO Y MIQUELÓN", viewValue: "SAN PEDRO Y MIQUELÓN" },
        { value: "SAN VICENTE Y GRANADINAS", viewValue: "SAN VICENTE Y GRANADINAS" },
        { value: "SANTA HELENA", viewValue: "SANTA HELENA" },
        { value: "SANTA LUCÍA", viewValue: "SANTA LUCÍA" },
        { value: "SANTA SEDE", viewValue: "SANTA SEDE" },
        { value: "SANTO TOMÉ Y PRÍNCIPE", viewValue: "SANTO TOMÉ Y PRÍNCIPE" },
        { value: "SENEGAL", viewValue: "SENEGAL" },
        { value: "SERBIA", viewValue: "SERBIA" },
        { value: "SEYCHELLES", viewValue: "SEYCHELLES" },
        { value: "SIERRA LEONE", viewValue: "SIERRA LEONE" },
        { value: "SINGAPUR", viewValue: "SINGAPUR" },
        { value: "SIRIA", viewValue: "SIRIA" },
        { value: "SOMALIA", viewValue: "SOMALIA" },
        { value: "SRI LANKA", viewValue: "SRI LANKA" },
        { value: "SUAZILANDIA", viewValue: "SUAZILANDIA" },
        { value: "SUDÁN", viewValue: "SUDÁN" },
        { value: "SUDÁN DEL SUR", viewValue: "SUDÁN DEL SUR" },
        { value: "SUECIA", viewValue: "SUECIA" },
        { value: "SUIZA", viewValue: "SUIZA" },
        { value: "SURINAM", viewValue: "SURINAM" },
        { value: "TAILANDIA", viewValue: "TAILANDIA" },
        { value: "TAIWÁN", viewValue: "TAIWÁN" },
        { value: "TANZANIA", viewValue: "TANZANIA" },
        { value: "TAYIKISTÁN", viewValue: "TAYIKISTÁN" },
        { value: "TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO", viewValue: "TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO" },
        { value: "TIERRAS AUSTRALES Y ANTÁRTICAS FRANCESAS", viewValue: "TIERRAS AUSTRALES Y ANTÁRTICAS FRANCESAS" },
        { value: "TIMOR ORIENTAL", viewValue: "TIMOR ORIENTAL" },
        { value: "TOGO", viewValue: "TOGO" },
        { value: "TONGA", viewValue: "TONGA" },
        { value: "TRINIDAD Y TOBAGO", viewValue: "TRINIDAD Y TOBAGO" },
        { value: "TURKMENISTÁN", viewValue: "TURKMENISTÁN" },
        { value: "TURQUÍA", viewValue: "TURQUÍA" },
        { value: "TUVALU", viewValue: "TUVALU" },
        { value: "TÚNEZ", viewValue: "TÚNEZ" },
        { value: "UCRANIA", viewValue: "UCRANIA" },
        { value: "UGANDA", viewValue: "UGANDA" },
        { value: "URUGUAY", viewValue: "URUGUAY" },
        { value: "UZBEKISTÁN", viewValue: "UZBEKISTÁN" },
        { value: "VANUATU", viewValue: "VANUATU" },
        { value: "VENEZUELA", viewValue: "VENEZUELA" },
        { value: "VIETNAM", viewValue: "VIETNAM" },
        { value: "WALLIS Y FUTUNA", viewValue: "WALLIS Y FUTUNA" },
        { value: "YEMEN", viewValue: "YEMEN" },
        { value: "YIBUTI", viewValue: "YIBUTI" },
        { value: "ZAMBIA", viewValue: "ZAMBIA" },
        { value: "ZIMBABUE", viewValue: "ZIMBABUE" }
    ];
export const $time = [
    {
        value: 'MES',
        viewValue: 'MES'
    },
    {
        value: 'DÍA',
        viewValue: 'DÍA',
    },
    {
        value: 'AÑO',
        viewValue: 'AÑO',
    }
];

export const $allFamily = {
    label: 'Parentesco',
    name: 'family',
    options: [
        {
            value: 'Padre',
            viewValue: 'Padre'
        },
        {
            value: 'Madre',
            viewValue: 'Madre',
        },
        {
            value: 'Hermanos',
            viewValue: 'Hermanos/as',
        },
        {
            value: 'Hijos',
            viewValue: 'Hijos/as',
        }
    ]
}
